export const data = [
  {
    id: "1",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " سفارشی ",
    markedAs: "",
  },
  {
    id: "2",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " سفارشی ",
    markedAs: "",
  },
  {
    id: "3",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " جدید ترین  ",
    markedAs: "",
  },
  {
    id: "4",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " جدید ترین  ",
    markedAs: "",
  },
  {
    id: "5",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " سفارشی ",
    markedAs: "",
  },
  {
    id: "6",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " پرفروش ترین  ",
    markedAs: "",
  },
  {
    id: "7",
    img: "/shopping.png",
    dis: "مبل چهار نفره مدل لوکس",
    price: "400000",
    colors: ["black", "orange"],
    category: " پرفروش ترین  ",
    markedAs: "",
  },
];

export const categoryData = [
  {
    id: "1",
    name: "مبل",
  },
  {
    id: "2",
    name: "لوستر",
  },
  {
    id: "3",
    name: "تخت خواب",
  },
  {
    id: "4",
    name: "میز و صندلی",
  },
];

export const products = [
  {
    id: "1",
    img: "/shopping2.jpg",
    dis: "مبل چهار نفره مدل لوکس",
    price: "9000000",
    colors: ["gray", "green", "blue"],
    category: "مبل",
    markedAs: "سفارشی",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "2",
    img: "/shopping1.jpg",
    dis: "مبل کلاسیک مدل چراغان ا مبل کلاسیک سه نفره مدل چراغان به همراه جلو مبلی و عسلی",
    price: "6400000",
    colors: ["red", "orange"],
    category: "مبل",
    markedAs: "پرفروش ترین",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "3",
    img: "/shopping3.jpg",
    dis: "مبل راحتی مینیمال بارسلون ساده - مازراتی ا Ali Sofa",
    price: "11000000",
    colors: ["black", "orange"],
    category: "مبل",
    markedAs: "جدید ترین",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "4",
    img: "/shopping4.jpg",
    dis: "لوستر گلد مدل رویان",
    price: "4200000",
    colors: ["black", "orange"],
    category: "لوستر",
    markedAs: "سفارشی",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "5",
    img: "/shopping5.jpg",
    dis: "صندلی اپن هیدیکا مبلمان مدل سوفیا طرح پشت کندویی",
    price: "3390000",
    colors: ["blue", "red"],
    category: "میز و صندلی",
    markedAs: "",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "6",
    img: "/shopping6.jpg",
    dis: "میز تحریر؛کامپیوتر چوب فلز مدل راد - کلیاف روشن / طوسی ا writing desk, metal wood computer, Rod model",
    price: "2800000",
    colors: ["gray", "orange", "blue"],
    category: "میز و صندلی",
    markedAs: "سفارشی",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "7",
    img: "/shopping7.jpg",
    dis: "میز تحریر و کامپیوتر دلسادکور مدل 51847 - سفید",
    price: "4000000",
    colors: ["gray", "brown"],
    category: "میز و صندلی",
    markedAs: "پرفروش ترین",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "8",
    img: "/shopping8.jpg",
    dis: "تخت خواب دونفره مدل فلورا - 1 عدد / با کشو / داشته باشد",
    price: "13600000",
    colors: ["gray", "orange", "brown"],
    category: "تخت خواب",
    markedAs: "پرفروش ترین",
    isAvailable: true,
    discountPrecent: 0,
  },
  {
    id: "9",
    img: "/shopping9.jpg",
    dis: "سرویس خواب لیزری کد bs_1100101 - طوسی / ست کامل دو نفره به همراه میز آرایش ۵ کشو و اینه و صندلی ودوعدد پاتختی ا Lazer bedset bs_1100101",
    price: "8000000",
    colors: ["gray", "yellow"],
    category: "تخت خواب",
    markedAs: "جدید ترین",
    isAvailable: true,
    discountPrecent: 0,
  },
];

export const designData = [
  {
    id: "1",
    img: "",
    place: "",
    author: "",
  },
];

export const productData = {
  title: "جدید ترین و پرفروش ترین ها",
  price: "هزار تومان",
  description: "کفش پیاده روی مردانه کفش سعیدی مدل 833M",
  color: "رنگ",
  size: "اندازه",
  quantity: "تعداد",
  total: "قیمت کل",
  groupBy: "دسته بندی",
  allProducts: "همه محصولات",
};

export const cardData = {
  products: "محصولات",
  title: "نام محصول",
  price: "قیمت",
  quantity: "تعداد",
  total: "کل",
  remove: "حذف",
};

export const decorationData = [
  {
    id: "1",
    type: "پزیرایی",
    img: "/decor1.jpg",
  },
  {
    id: "2",
    type: "پزیرایی",
    img: "/decor2.jpg",
  },
  {
    id: "3",
    type: "آشپزخانه",
    img: "/decor3.jpg",
  },
  {
    id: "4",
    type: "آشپزخانه",
    img: "/decor4.jpg",
  },
];
